---
name: Run Relevant Checks

on: [push]

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: container_app_environment_custom_dns_suffix
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.*'
          terraform_wrapper: false
      - run: make tools
      - run: make acctests
        env:
          TF_ACC: '1'
          TESTARGS: '-parallel=1 -run=TestAccContainerAppEnvironment_completeWithCustomDnsSuffix'
          SERVICE: 'containerapps'
          TESTTIMEOUT: '60m'
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_TEST_LOCATION: ${{ secrets.ARM_TEST_LOCATION }}
          ARM_TEST_LOCATION_ALT: ${{ secrets.ARM_TEST_LOCATION_ALT }}
          ARM_TEST_LOCATION_ALT2: ${{ secrets.ARM_TEST_LOCATION_ALT2 }}
  pr-check:
    name: PR checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: make tools
      - run: make pr-check
      - run: git status